jenkinsdata:
 build: jenkins-data
jenkinsmaster:
 build: jenkins
 volumes_from:
  - jenkinsdata
 ports:
  - "50000:50000"
jenkinsnginx:
 build: nginx
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkinsmaster
